services:
  - type: web
    name: funpay-bot
    env: docker
    repo: https://github.com/ваш-логин/funpay-bot
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_TOKEN
        sync: false
      - key: LOG_CHAT_ID
        sync: false
      - key: PROFIT_CHAT_ID
        sync: false
      - key: LOG_THREAD_ID
        sync: false
      - key: PROFIT_THREAD_ID
        sync: false
      - key: ADMIN_IDS
        sync: false
